const tempData = [
  {
    id: 1412,
    city: 'Батайск',
    region: 'Ростовская область',
    country: 'Россия',
    shortCity: '',
    shortRegion: 'Ростовская обл.',
    shortCountry: '',
    engCity: 'Bataysk',
    engRegion: 'Rostov region',
    engCountry: 'Russia',
    iso2: 'RU',
    iso3: '',
    comment: '',
    phoneNumber: '786354',
    startNumber: '78635400000',
    endNumber: '78635499999',
    minLenghtCode: '11',
    maxLenghtCode: '15',
    dateEnter: '',
    dateCancle: '',
    operator: '',
    engOperator: '',
  }, {
    id: 14122,
    city: 'Ростов-на-Дону',
    region: 'Ростовская область',
    country: 'Россия',
    shortCity: '',
    shortRegion: 'Ростовская обл.',
    shortCountry: '',
    engCity: 'Rostov-on-Don',
    engRegion: 'Rostov region',
    engCountry: 'Russia',
    iso2: 'RU',
    iso3: '',
    comment: '',
    phoneNumber: '78632',
    startNumber: '78632000000',
    endNumber: '78632999999',
    minLenghtCode: '11',
    maxLenghtCode: '15',
    dateEnter: '',
    dateCancle: '',
    operator: '',
    engOperator: '',
  }, {
    id: 14132,
    city: 'Морозовск',
    region: 'Ростовская область',
    country: 'Россия',
    shortCity: '',
    shortRegion: 'Ростовская обл.',
    shortCountry: '',
    engCity: 'Morozovsk',
    engRegion: 'Rostov region',
    engCountry: 'Russia',
    iso2: 'RU',
    iso3: '',
    comment: '',
    phoneNumber: '786314',
    startNumber: '78631400000',
    endNumber: '78631499999',
    minLenghtCode: '11',
    maxLenghtCode: '15',
    dateEnter: '',
    dateCancle: '',
    operator: '',
    engOperator: '',
  }, {
    id: 141322,
    city: 'Лондон',
    region: '',
    country: 'Великобритания',
    shortCity: '',
    shortRegion: '',
    shortCountry: '',
    engCity: 'London',
    engRegion: '',
    engCountry: 'UK',
    iso2: 'GB',
    iso3: 'GBZ',
    comment: '',
    phoneNumber: '',
    startNumber: '',
    endNumber: '',
    minLenghtCode: '',
    maxLenghtCode: '',
    dateEnter: '',
    dateCancle: '',
    operator: '',
    engOperator: '',
  }, {
    id: 23142,
    city: 'Барановичи',
    region: 'Брест',
    country: 'Беларусь',
    shortCity: '',
    shortRegion: '',
    shortCountry: '',
    engCity: 'Baranovichi',
    engRegion: 'BREST',
    engCountry: 'Belarus',
    iso2: 'BY',
    iso3: '',
    comment: '',
    phoneNumber: '375163',
    startNumber: '375163000000',
    endNumber: '375163999999',
    minLenghtCode: '112',
    maxLenghtCode: '15',
    dateEnter: '',
    dateCancle: '',
    operator: '',
    engOperator: '',
  }, {
    id: 12513,
    city: 'Жабинка',
    region: 'Брест',
    country: 'Беларусь',
    shortCity: '',
    shortRegion: '',
    shortCountry: '',
    engCity: 'Zhabinka',
    engRegion: 'BREST',
    engCountry: 'Belarus',
    iso2: 'BY',
    iso3: '',
    comment: 'comment comment comment',
    phoneNumber: '3751641',
    startNumber: '375164100000',
    endNumber: '375164199999',
    minLenghtCode: '12',
    maxLenghtCode: '15',
    dateEnter: '',
    dateCancle: '',
    operator: '',
    engOperator: '',
  }, {
    id: 123415,
    city: 'Бобруйск',
    region: 'МОГИЛЕВ',
    country: 'Беларусь',
    shortCity: '',
    shortRegion: '',
    shortCountry: '',
    engCity: 'Bobruisk',
    engRegion: 'Mogilev',
    engCountry: 'Belarus',
    iso2: 'BY',
    iso3: '',
    comment: '',
    phoneNumber: '375225',
    startNumber: '375225000000',
    endNumber: '375225999999',
    minLenghtCode: '12',
    maxLenghtCode: '15',
    dateEnter: '',
    dateCancle: '',
    operator: '',
    engOperator: '',
  }
]

export default tempData;
