const Reports = [

{id: 1,
open_date: '12-12-2022',
close_date:' ',
accept_date: '13-12-2022',
comment:'test',
qual_watched:10,
qual_label:2,
qual_open:12,
qual_net:3,
creator:'operator',
who_closed:'you',
who_accept:'you',
number_report:1},
{id: 2,
    open_date: '14-12-2022',
    close_date:'21-12-2022',
    accept_date: '15-12-2022',
    comment:'qqq',
    qual_watched:13,
    qual_label:6,
    qual_open:18,
    qual_net:2,
    creator:'operator',
    who_closed:'admin',
    who_accept:'admin',
    number_report:1},
]
export default Reports